title: Fonts in Fashion
description: "How Fashion Brands use type "
footer_text: "Copyright 2021 "
header_feature_image: ../uploads/photo-1566399468572-74fbd5cfe034.webp
header_text: Fonts In Fashion
header_text_color: "#ffffff"
bannerheight: 40vmax
navbarheight: 55px
logo: ../uploads/logo.png
favicon: ../uploads/favicon.ico
gridlayout: true
fixednavbar: false
upzoom: true
