title: .
description: "How Fashion Brands use type "
footer_text: "Copyright 2021 "
header_feature_image: ../uploads/fonts-in-fashion.png
header_text: Fonts In Fashion
header_text_color: "#000000"
bannerheight: 40vmax
navbarheight: 55px
logo: ../uploads/logo.png
favicon: ../uploads/favicon.ico
gridlayout: true
fixednavbar: false
upzoom: true
